### PR TITLE
Creation of markdown file

### PR DESCRIPTION
**Pull request by ZacharySabourin**
Commit for [issue 465](https://github.com/openhwgroup/openhwgroup.org/issues/465)

### CODE REVIEW

**Comment by rickoco** [comment]
@chrisguindon @ZacharySabourin the release is not shown in the Deploy Preview...

**Comment by ZacharySabourin** [comment]
[Here is the requested page](https://deploy-preview-466--eclipsefdn-openhwgroup.netlify.app/news/2022/06/20/openhw-group-announces-risc-v-based-core-v-mcu-development-kit-for-iot-built-with-open-source-hardware-software/)

**Comment by chrisguindon** [comment]
@rickoco The homepage requires an entry in Eclipse Newsroom. The Eclipse Marketing team can take care of creating that once the page is live. //cc @shanda-eclipse

**Comment by rickoco** [comment]
> @rickoco The homepage requires an entry in Eclipse Newsroom. The Eclipse Marketing team can take care of creating that once the page is live. //cc @shanda-eclipse

ok thx @ZacharySabourin and @chrisguindon - ready to deploy

**Comment by rickoco** [comment]
@shanda-eclipse @chrisguindon pls publish by EoD today, so this is live by central Europe time tmw AM

**Comment by rickoco** [comment]
thx @chrisguindon - really appreciate your support with getting this release out EoD today.  This is a major announcement for the OpenHW ecosystem with many member companies involved.

**Review by autumnfound — APPROVED** [review]

**Pull request merged**
