### PR TITLE
Add Nov 30 2022 blog post

### LINKED ISSUE #548: New blog post
@chrisguindon - is it possible to get this blog post up on Wed Nov 30th?

https://docs.google.com/document/d/1_Z3uvOHcFoOH0VLsnose66buG7JWNHoXRsNWx3lvU8s/edit?usp=sharing

please use the following URL for the blog

https://www.openhwgroup.org/resources/blog/core-v-cva6-open-source-manycore-risc-v/

### PR DESCRIPTION
**Pull request by oliviergoulet5**
Resolves #548

### CODE REVIEW

**Comment by chrisguindon** [comment]
The netlify build is expected to fail here. We should review this using https://preview-549--openhwgroup-org.eclipsecontent.org/

**Comment by oliviergoulet5** [comment]
+1 from Rick

**Comment by chrisguindon** [comment]
I did notice some of the images were quite big. I assume you couldn't optimize them more than that?

**Review by ZacharySabourin — COMMENTED** [review]
I think the Intel pathfinder file and the cluster file size might be a bit too large. Otherwise LGTM!

**Comment by oliviergoulet5** [comment]
I'll create a second patch to decrease the sizes.

**Pull request merged**
