### PR TITLE
update about us, delete one member and add two members

### LINKED ISSUE #220: update https://www.openhwgroup.org/about-us/
Could you please update the staff page under About US as follows. Please follow same formatting for linked in link, etc. as the existing profiles

Delete Jim Parisien

Add: 

Duncan Bees – Staff Member
Duncan Bees is Director, Technical Programs of the OpenHW Group and the Eclipse Foundation.  He manages the open-source engineering process supporting industrial-quality design and verification of the IP curated by the OpenHW Group, as well as the SW tools, FPGA, SoC implementations, and board level designs that support this ecosystem. Duncan has previously held executive roles with the Home Gateway Initiative (HGI) and the Digital Living Network Alliance (DLNA) and has contributed to many worldwide standards and technology initiatives. He managed R&D and product research for telecom, wireless and semiconductor companies. Duncan holds a bachelor’s degree in Applied Science from the University of British Columbia, a master’s degree with Honours in Electrical Engineering from McGill University, and has completed extensive study in machine learning, software, and data analytics. He is a certified Project Management Professional and Certified Scrum Master. 
www.linkedin.com/in/duncanbees

Florian Zaruba - Staff Member
Florian is the OpenHW Group Director of Engineering, HW & SW Task Groups and a PhD student at the Integrated Systems Laboratory of ETH Zurich. His research interests include exploring new directions in energy-efficient high-performance computing. He is also the principle architect of CVA6 (Ariane). His experience includes a strong background in physical design with more than eight ASICs designed, manufactured and tested. Florian holds a Bachelor of Science degree from TU Wien and a master’s degree from ETH Zurich. See the following link for further information. http://asic.ethz.ch/authors/Florian_Zaruba.html
 https://www.linkedin.com/in/florianzaruba/

### PR DESCRIPTION
**Pull request by flora8984461**
Fix #220 

Signed-off-by: Yi Liu <yi.liu@eclipse-foundation.org>

### CODE REVIEW

**Comment by chrisguindon** [comment]
@DBees can you confirm that the changes are good? 

https://deploy-preview-221--eclipsefdn-openhwgroup.netlify.app/about-us/

**Review by chrisguindon — APPROVED** [review]
LGTM - Waiting for a +1 from @DBees  before we merge this.

**Comment by DBees** [comment]
looks good thank you

**Review by DBees — APPROVED** [review]
Great thanks

**Pull request merged**
