### PR TITLE
feat: Reorder Core-V DevKits page, update text, and add SDK features

### PR DESCRIPTION
**Pull request by ZacharySabourin**
Resolves https://github.com/openhwgroup/openhwgroup.org/issues/645

### CODE REVIEW

**Comment by chrisguindon** [comment]
@ZacharySabourin Is it possible to shrink the size of the image?

**Comment by ZacharySabourin** [comment]
I reduced it from 1.7MB already. I'll see what I can do without losing too much quality

**Comment by ZacharySabourin** [comment]
@chrisguindon I realize what happened. I had compressed it, but when I cropped the image a bit, it got larger somehow and I didn't seem to notice. I did things in reverse order and it's much better.

**Review by oliviergoulet5 — APPROVED** [review]
LGTM

**Pull request merged**
