### PR TITLE
Membership section draft created + associated changes

### PR DESCRIPTION
**Pull request by autumnfound**
Signed-off-by: Martin Lowe <martin.lowe@eclipse-foundation.org>

### CODE REVIEW

**Comment by autumnfound** [comment]
@rickoco We've got a prototype of the membership content that you asked for available for preview on a staging site, available there -> https://deploy-preview-89--eclipsefdn-openhwgroup.netlify.com. To see the pages, you can use the "Membership" link in the header of the home page.

Keep in mind that this is a prototype and not all content is present or 100% up to date. I grabbed some of the updates you made yesterday but would go through it again before we push up a final version. As well we would add the rest of the members to the member explore page once we get your go-ahead.

To get content going, I split the members/partners into 3 groups, members, partners, and gold partners. These are placeholder names and can be easily updated. The split to 3 groups is in anticipation of the currently active issue (#85), in that partners are being split on some level.

Please let us know what you think!

**Comment by chrisguindon** [comment]
This is a great start!

@rickoco, here's a list of all the pages that @autumnfound created so far:

1. https://deploy-preview-89--eclipsefdn-openhwgroup.netlify.com/membership/
2. https://deploy-preview-89--eclipsefdn-openhwgroup.netlify.com/membership/members/
3. https://deploy-preview-89--eclipsefdn-openhwgroup.netlify.com/membership/contact/

@autumnfound Here's my feedback on what's been done so far:

1.  I would expect to see the sidebar on all membership sub-pages
2. add a bit of padding-top to sidebar. I find that it's too close to the "jumbotron".
3. Remove the jumbotron header on https://deploy-preview-89--eclipsefdn-openhwgroup.netlify.com/membership/members/ and move the heading in the content area
4. The link to the membership agreement is missing on https://deploy-preview-89--eclipsefdn-openhwgroup.netlify.com/membership/contact/ 
5. Missing space between signed and Membership on  membership/contact/ 
6. Please reduce the padding-bottom in the jumbotron for https://deploy-preview-89--eclipsefdn-openhwgroup.netlify.com/membership/

**Comment by autumnfound** [comment]
I've updated for the mentioned issues! Same URLs as before, as Netifly doesn't change between builds on the same pull request.

**Comment by rickoco** [comment]
@autumnfound @chrisguindon 
Guys - looks good so far.  Few changes...

1. no need to tier partners (remove gold partners).  So just Members and Partners
2. Membership page - change orange graphics to OpenHW colours green or blue
3. Membership page - perhaps a "Become a Member" button at the bottom of the text?  I know we have the sidebar, but a button may seem more intuitive.

Thanks for the progress gents!

**Comment by autumnfound** [comment]
> @autumnfound @chrisguindon
> Guys - looks good so far. Few changes...
> 
>     1. no need to tier partners (remove gold partners).  So just Members and Partners
> 
>     2. Membership page - change orange graphics to OpenHW colours green or blue
> 
>     3. Membership page - perhaps a "Become a Member" button at the bottom of the text?  I know we have the sidebar, but a button may seem more intuitive.
> 
> 
> Thanks for the progress gents!

If you check the preview, you should see the mentioned updates made! Let me know if there is anything else

**Comment by chrisguindon** [comment]
Thanks @rickoco 

Just so you know, we are most likely to have this merged in tomorrow.

We implemented some quick hacks so that we can get your approval on the changes and now that we have that, we need to clean up some of this code before we push this live!

**Pull request merged**
