### PR TITLE
Add Intel Pathfinder for Risc-V Launch blog post

### LINKED ISSUE #503: OpenHW Group Blog for posting
can we please post this blog on the OpenHW website under the blog page and also on the News Page.  It would be great if we can get this posted by Thursday September 1. 
[Intel Pathfinder OpenHW blog final.docx](https://github.com/openhwgroup/openhwgroup.org/files/9455074/Intel.Pathfinder.OpenHW.blog.final.docx)

### PR DESCRIPTION
**Pull request by oliviergoulet5**
Resolves #503

### CODE REVIEW

**Comment by rickoco** [comment]
thx @oliviergoulet5 - pls delete this sentence as it is repeated just above the new para we added "Start your journey with Intel® Pathfinder for RISC-V at [pathfinder.intel.com](https://pathfinder.intel.com/)"

**Comment by rickoco** [comment]
@oliviergoulet5 - the Blog title should be updated to show the following capitalization: Intel Pathfinder for RISC-V Launch Bolstered by OpenHW Group CORE-V Family Open Source Cores

**Comment by oliviergoulet5** [comment]
I have made the changes. @rickoco

**Comment by rickoco** [comment]
Thx @oliviergoulet5 - looks good.  Please deploy and this Blog post should also show as a News item on the home page.

**Comment by oliviergoulet5** [comment]
Sure, I'll hand it to the web team to review and we'll deploy it asap.

As for this getting added to the news section, we'll need to make a change to an API. @autumnfound

**Comment by ZacharySabourin** [comment]
> Resolves #508

You accidentally put the PR here instead of the issue :P

**Comment by rickoco** [comment]
@oliviergoulet5 - don't think a new api is needed, the Blog just needs to be submitted as a news item and I'm asking for that to be pushed through as the blog post is deployed.

**Review by autumnfound — APPROVED** [review]

**Comment by rickoco** [comment]
thx - let me know when its live on the front page news reel

**Comment by chrisguindon** [comment]
@oliviergoulet5 To update the OpenHWGroup homepage, you need to submit the info via https://newsroom.eclipse.org/node/add/news

**Comment by rickoco** [comment]
@oliviergoulet5 - I just noticed the logos are not on the blog post.  Pls add the following logos on the same line, spaced appropriately at the top of the blog post...

04-Intel Classis Blue  Energy Spark PathFinder for RISC-V Stacked Logo

CORE-V-landscape®

**Pull request merged**
