### PR TITLE
Migrate EF websites to our new preview framework

### PR DESCRIPTION
**Pull request by chrisguindon**
Related to https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1978

### CODE REVIEW

**Comment by oliviergoulet5** [comment]
@chrisguindon Can we wait until [this issue](https://github.com/openhwgroup/openhwgroup.org/issues/523) closes until we migrate away from netlify for OpenHW? The netlify build is being used by Intel for a logo approval.

**Comment by chrisguindon** [comment]
@mbarbero I tried to configure the jenkins instance but builds are falling without an obvious error message. This is the first Github website that I am configuring with our new preview framework.

https://foundation.eclipse.org/ci/webdev/job/public/job/openhwgroup.org

**Comment by mbarbero** [comment]
I was expecting some minor issues like this as we've not been running for repos GitHub for quite a while. It was a little regression after a refactoring. This is [fixed now](https://gitlab.eclipse.org/eclipsefdn/it/releng/jenkins-pipeline-library/-/compare/v0.9.6...v0.9.7?from_project_id=1685&straight=false).

**Review by mbarbero — APPROVED** [review]

**Comment by chrisguindon** [comment]
> I was expecting some minor issues like this as we've not been running for repos GitHub for quite a while. It was a little regression after a refactoring. This is [fixed now](https://gitlab.eclipse.org/eclipsefdn/it/releng/jenkins-pipeline-library/-/compare/v0.9.6...v0.9.7?from_project_id=1685&straight=false).

It's also working for osdforums! Thanks @mbarbero https://github.com/openhwgroup/osdforum.org/pull/106

**Pull request merged**
