### PR TITLE
feat: Update membership contact form to verison with registered logo

### PR DESCRIPTION
**Pull request by ZacharySabourin**
Resolves https://github.com/openhwgroup/openhwgroup.org/issues/491

### CODE REVIEW

**Comment by ZacharySabourin** [comment]
+1 from Zahra

**Review by autumnfound — CHANGES_REQUESTED** [review]
There is a new PDF in the issue, update and I'll push

**Comment by ZacharySabourin** [comment]
Yeah. The form still hasn't been confirmed as final yet

**Comment by ZacharySabourin** [comment]
+1 from Duncan
@autumnfound @ericpoirier @chrisguindon @oliviergoulet5

**Review by ericpoirier — APPROVED** [review]

**Pull request merged**
